version: '3.7'

services:
  surging.hero.auth:
    environment:
      Register_Conn: ${REGISTER_CONN:-hero.consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-hero.rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      Environment: ${ENVIRONMENT:-Development}
      ForceDisplayStackTrace: ${FORCED_DISPLAY_STACKTRACE:-false}
      DbType: ${AUTH_DB_TYPE:-Mysql}
      ConnectionString: ${AUTH_DB_CONN}
      SwaggerTitle: "surging.hero.auth"
      SwaggerDes: "身份认证与授权服务组件API文档"
      SupportName: "liuhongliang"
      SupportEmail: "1029765111@qq.com"
      InitAction: "${INIT_ACTION:-false}"
    ports:
      - "18081:8080"

  surging.hero.basicdata:
    environment:
      Register_Conn: ${REGISTER_CONN:-hero.consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-hero.rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      ForceDisplayStackTrace: ${FORCED_DISPLAY_STACKTRACE:-false}
      DbType: ${BASICDATA_DB_TYPE:-Mysql}
      ConnectionString: ${BASICDATA_DB_CONN}
      SwaggerTitle: "surging.hero.basicdata"
      SwaggerDes: "系统基础数据服务组件API文档"
      SupportName: "liuhongliang"
      SupportEmail: "1029765111@qq.com"
      InitAction: "${INIT_ACTION:-false}"
    ports:
      - "18082:8080"

  surging.hero.organization:
    environment:
      Register_Conn: ${REGISTER_CONN:-hero.consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-hero.rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      ForceDisplayStackTrace: ${FORCED_DISPLAY_STACKTRACE:-false}
      DbType: ${ORGANIZATION_DB_TYPE:-Mysql}
      ConnectionString: ${ORGANIZATION_DB_CONN}
      SwaggerTitle: "surging.hero.organization"
      SwaggerDes: "组件机构服务组件API文档"
      SupportName: "liuhongliang"
      SupportEmail: "1029765111@qq.com"
      InitAction: "${INIT_ACTION:-false}"
    ports:
      - "18083:8080"

  surging.hero.gateway:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
    ports:
      - "10080:80"